- 
  hosts: win
  tasks:
     - name: Create a partition with drive letter D and size 5 GiB
        win_partition:
                drive_letter: D 
                partition_size: 5 GiB    
                disk_number: 1
                log_path: c:/Scripts/ansible_wu.txt


